### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by po5i**

### CODE REVIEW

**Comment by po5i** [comment]
Hey @kevinweber would you mind to take a look if the translation contribution is good? (I'm a native speaker BTW, so you don't need to worry for Grammar too much 😅)

**Comment by kevinweber** [comment]
Hey @po5i, thank you so much for contributing! That translation looks good to me. 
Would you like to add yourself to the list of translators in the [readme.txt](https://github.com/kevinweber/lazy-load-for-videos/blob/master/readme.txt#L43) file before I merge your change? It'll show on https://wordpress.org/plugins/lazy-load-for-videos/

**Comment by po5i** [comment]
Thanks for the review @kevinweber.

I've added myself to the list as requested.

**Comment by po5i** [comment]
@kevinweber is any other change required before it's considered ready?

**Comment by kevinweber** [comment]
Thanks @po5i for your 2nd contribution to this project :) I just published the translation with version 2.7.7. Your name and website is now linked on https://wordpress.org/plugins/lazy-load-for-videos/.
If you haven't given this project a five-star rating yet, please do so [here](https://wordpress.org/support/plugin/lazy-load-for-videos/reviews/?filter=5).

**Comment by kevinweber** [comment]
@po5i For some reason, your translation doesn't show up as an officially supported language in the dropdown provided by WordPress:
Screen Shot 2019-11-04 at 9 33 18 PM

Could it be that this is the case because your language is `es_MX`? Should we change it to `es_ES` instead?

**Comment by po5i** [comment]
@kevinweber That's weird. In any case, I can create a PR to change it to `es_ES`. I considered myself my Spanish very neutral so it shouldn't be an issue 😉

**Pull request merged**
